### ISSUE TITLE
How to fix RO Restart "The server has denied your connection for unknown reason (30)" ?

### ISSUE THREAD

**Issue by mhakulit** [OpenKore/openkore#1023]
I think Ragnarok Restart can detect bot apps ?
can anyone help me to fix it ?

![image](https://user-images.githubusercontent.com/30317087/29813738-9180da06-8cdd-11e7-87db-e784f7c8f525.png)

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by nemisawesome** [comment]
This happens when you send un-updated packets to the server. Update your OpenKore and then try again, or remove the commands/macros using the un-updated commands. What is your bot configured to do as soon as it connects? (Buy, Sell, Cart, Shop, etc?) Why use the template if you do not actually fill it out what so ever?

**Comment by Mortimal** [comment]
@mhakulit use latest openkore, check it every time u want to run bot.
