### ISSUE TITLE
how to patch a bot file once have update?  

### ISSUE THREAD

**Issue by notsobotuser** [OpenKore/openkore#1087]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Bombahee** [comment]
I'm having a hard time with this too,

all i do is, download the new version of openkore, extract it, move config.txt and some other files to the new openkore version and delete the old bot, so if you got a 4 bots, it needs manually move all those old config to the new version one by one.

is there other way to overwrite only the old files with the new updated files on the old version of openkore?

**Comment by notsobotuser** [comment]
same i got 3 only but kindly lazy to do. so any please?

**Comment by iRObotzz** [comment]
Downloading a whole new openkore is the best way to ensure it might work, but if you copy/paste your config file, make sure there isint a new update to the actual config file! 

There is also a possibilty to go through the list to see which files where changed with the last 24hours after an update and just download those files, or copy/paste those new updated files into your kore folders. 

IMO the easiest is just to move the config(if its unchanged) and the pickupitems/itemscontrol/moncontrol files, since these are only files changed by casual botters like myself!

**Comment by imic23** [comment]
Github have a desktop application. Where it only downloads the updated file/folders, instead of downloading a whole new rar file of openkore.

**Comment by joecabezas** [comment]
I just forked this repo and manage a separate branch after any update I just `git rebase` against master, and voila

**Comment by lututui** [comment]
git fetch
git stash save
git rebase origin/master
git stash pop

or

git stash save
git pull --rebase origin/master
git stash pop

**Comment by windhamwong** [comment]
2 ways to update OpenKore.
1. Download from http://github.com/openkore/openkore. Replace files EXCEPT config folder.
2. Use git. You can use any git tools to update your files. Referring to the comment by @lututui 

I highly suggest you to read this as well, http://openkore.com/index.php/Run_multiple_bots_from_the_same_.exe
