### ISSUE TITLE
 UNKNOWN_STATUS_994,  UNKNOWN_STATUS_993??

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1146]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

## ------------------ Bug Report Template ------------------
i tried to search but i dont see any solution to this? correct me if im wrong . sorry. 

should i worry about this unknown status or should i just leave it?

**Comment by sctnightcore** [comment]
do not mind !

**Comment by koodpzok** [comment]
table/status_id_handle.txt You can modify there at ur will

**Comment by windhamwong** [comment]
@gr4ndmasterz The reason you seeing this weird status name because servers might use different ID (i.e. 994 and 993 in this case) for the different statuses. If you know the name of the statuses, you can add them back to `table/status_id_handle.txt`.

At last, if you know the name, please reopen this issue and put it here so we can update the source for you. Thank you.
