### ISSUE TITLE
iRO Chaos Renewal Server: Issues with lockmap and area of botting

### ISSUE THREAD

**Issue by shaohui89** [OpenKore/openkore#1184]
Hey guys,

I have issues with botting in a specific area. For example, if i were to input the map at mjo_dun02.

The bot is unable to walk itself to the lockmap location from its current location.

Did some of the maps changed or portals issues? Is there a way to solve this? I tried many locations but most of them dont work.

Please advise.

Much appreciated.

**Comment by fadreus** [comment]
This probably solve your problem #1069

**Comment by shaohui89** [comment]
@fadreus it doesnt work bro. lol.

**Comment by shaohui89** [comment]
Ignoring excessive use 'c' in conversation with npc.
According to the given NPC instructions, menu item 3 must now be selected, but there are only 2 menu items.
Using method '0' defined on config key 'npcWrongStepsMethod' to deal with the error.
Cleaning all remaining conversation steps, please input more steps using commands.

**Comment by fadreus** [comment]
That error is due to incorrect NPC conversation. You can try configure NPC conversation in `portals.txt` if you are going to `lockMap` using NPC. If the error shows something like "Unable to use portal at X Y" you can use macro something like this;


```
automacro Portals {
	console /Unable to use portal/
	call {
		do move 0
	}
}
```

Assuming there is only 1 portal in your screen.

**Comment by shaohui89** [comment]
@fadreus nothing working bro. care to share your files except the config?

**Comment by fadreus** [comment]
I'm using latest kore, you can download the new one and rather than copy-paste your old `control` folder, setup a new one. When I read `'mjo_dun02'` I recall reading somewhere there are few people having issues around aldebaran too, mine happen to be at yuno.

If that doesn't work, give more extra details like
-Save point
-Lockmap
-Error message
-Screenshot
-Anything that odd

_*I recommend using TortoiseSVN to simply check updates regularly to avoid conflict._

**Comment by alisonrag** [comment]
any update?

**Comment by Fadreus** [comment]
Up
