### ISSUE TITLE
phRO connection 

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#1225]
###### Summary: 
Agroup in one issue the attempts to connect to phRO server
###### Affected configuration(s)/ file(s):
pro connection files

###### Benefits: connect to phRO server

References:
#1220 
#1194 
#1188 
#1171 
#1151 
#1142 
#1137 
#1221 
#1219 
#677

**Comment by fadreus** [comment]
#1229

**Comment by yakisoba2009** [comment]
Any news? I just saw someone use openkore xkore1 and it's really legit but they won't share it since there are only a few people doing it.

**Comment by fadreus** [comment]
The only thing similar I found to XKore 1 is Pixel Bot..
If pixel bot, it's only a few because anyone need to pay for the bot.
Not sure what are they (Since I don't speak/read tagalog).

**Comment by yakisoba2009** [comment]
@fadreus pixelbot uses macro commands of mouse and keyboard to find pixels within the ragnarok window to attack and loot. It works but not as efficient as openkore and still very much buggy and unresponsive to some loots. 

I spoke with someone using xkore1 but doesn't want to share because they are the only few. 

Only thing that bothers me is how the devs could not figure how to get openkore to work but some people can. 

I'm thinking that they already made a working one but doesn't want to release it

**Comment by fadreus** [comment]
If it bothers you, here some points why:

- Dev team also human who still study / working.

- Probably no dev interested in pRO (or even playing it, it's new and already dead before 🤣)

- Doing Openkore Project doesn't pay their bills.

- Not that they couldn't, probably just busy with life.

- Some people who can make it working is probably PH Community (Who don't like sharing and greedy LOL).

- If they had a working one and don't want to release it, it's their choice. You don't build a house with all your hard work just to let strangers stay in your new house, right?  😂 😂 😂

**Comment by yakisoba2009** [comment]
Well come to think of it, if they made a working openkore for pRO there are a lot of people who will buy it for 100$. 

Meaning it would be beneficial for them to try and spend time doing it if it's possible. I for one would pay 100$ for it. People won't even complain and would be more than happy if they do intend to sell their work.

There are hundreds of players willing to pay 100$ for a working openkore pRO bot. 

100 players already equals to $10,000

**Comment by yakisoba2009** [comment]
@fadreus that's enough to pay their bills don't you think?

**Comment by Youtouchmytralala** [comment]
You mad, people. You want free bot to sell billions of zeny and blame devs because they cant give you what you want.

**Comment by yakisoba2009** [comment]
@youtouchmytralala who's mad? Apparently, you didn't even take the time to read the previous posts. I don't see anyone crying in this thread.

**Comment by Youtouchmytralala** [comment]
So bring you people with 10000 and give it to developers, untill then your words mean nothing.

**Comment by yakisoba2009** [comment]
@youtouchmytralala lol there's already a page in the Philippines for people wanting to buy bots. I didn't come here to argue with anyone, I am just stating there are a lot of people willing to pay for openkore bots. And if they are able to hardware lock their openkore program that means people wouldn't be able to make it work unless they pay the developer.

**Comment by fadreus** [comment]
Hahaha.. Chill guys. We are here to help each other, not bury one another 😌.
[You might wanna read the story of Kore here](http://openkore.com/index.php/OpenKore)
If you had the experience, struggling with something like Apez since then, you might understand why 😂😂.

**Comment by drayl666** [comment]
@yakisoba2009 aiyo bro could I ask for assistance? I might have some ideas that may fix your issue as well.

**Comment by daniel0994** [comment]
@yakisoba2009  heya any idea what application pixelBot use to create those macro?

**Comment by yakisoba2009** [comment]
@daniel0994 blue eye macro, I heard there's a tutorial in the website's forum
@drayl666 I dont have much to help you bro, trust me Im in the same boat as you

**Comment by jonelle1990** [comment]
BEM or blue eye macro is already dead in ROPH however they're using another program just like i have.

**Comment by daniel0994** [comment]
@jonelle1990 mind sharing?, I tried other macro but unfortunately mouse click and keyboard press is block in ROPH

**Comment by bebox123** [comment]
Nah, don't ask for that Jonelle, he's not sharing it. I know that person, his FB account is Jonelle Sambat. He's just leeching here in openkore because he can't bypass it and now he's not sharing it. He even sells openkore bot in iRO page. To those people who want to do the pixel bot, here's the blue eye macro.

**Comment by daniel0994** [comment]
@bebox123 @yakisoba2009  thx will try creating my own.  best regards pips

**Comment by jonelle1990** [comment]
lol using a blue eye macro? hahahaha GOODLUCK hahahaha

**Comment by bebox123** [comment]
Don't you know how to bypassed it? How ironic you can bot using pixel bot but can't bypass BEM on ROPH. Atleast I didn't sell working openkore bots in iRO RE:Start haha. You want some screenshots of you selling openkore in different groups in facebook?

**Comment by yakisoba2009** [comment]
If only devs will sell working ROPh openkore bots. One can dream :'(

**Comment by rophbotprogram** [comment]
Look at this video it seems legit.
https://web.facebook.com/ragnarokph2017botprogram/videos/1381392228638471/

**Comment by yakisoba2009** [comment]
Lol he's promoting his own page which is clearly a scam, din't believe this guy @rophbotprogram

**Comment by rophbotprogram** [comment]
Promoting my page? Check the video I just saw that on facebook ragnarok group idiot.,

**Comment by k1ngJ** [comment]
> Only thing that bothers me is how the devs could not figure how to get openkore to work but some people can.

^WOW. How ungrateful people can be. Remember, developers are doing this on their free time. Botting is a privilege not a right. Stop being so entitled, lol.

@yakisoba2009 Bring me the $10,000 and I'll release my fully functional Openkore fork that is working since day 3 of OBT.

**Comment by sctnightcore** [comment]
@k1ngJ  HAHAHAHAHAHAHA

**Comment by yakisoba2009** [comment]
@k1ngJ how was that being ungrateful and entitled?? I was simply  curious how openkore devs weren't able to figure it out while others did and it has been already 4 months since release so it has bothered me if openkore really did exist for roph before. What I don't also get is why some of you don't get that I'm just starting a dicussion and there is no need to get triggered. 

Obviously, I can't bring you $10,000 alone, but you can easily make that if you wish to do so

**Comment by fadreus** [comment]
A discussion answer for "Why dev can't figure it out' is because: _(I deleted my previous comment because I thought it would bring chaos, but seems it's already here, let me make it clear for you)_😌😌

- No dev get paid doing openkore. Bills are paid monthly & working overtime (fixing for PH server) for payment that no guarantee will feed them for the next month isn't worth the gamble. If doing Kore easily get $10,000 Don't you think anyone will be Bill Gates by now?😮

- If program can easily locked like you think it would, why Microsoft and other big companies have cracked version everywhere? Why Gravity can't even lock access for bot? Don't it make you curious?😮

- If you thinking that anyone (PH player) would giving dev $100 PER DEV Contributed to this Openkore (currently 37), don't you think each person need to give $3,700 for 1 bot? Or you think $100 ÷ 37 = $2.7 only for dev to keep them alive? If you think only 1 person could maintain Openkore, take a look at other RO Bot history. Most (ALL) of them are DEAD. 😕

- If you think maintaining openkore doesn't take too much time, why would no one fix stuff instantly? Why would even when server is down, took the whole team (Publisher) few hours to bring them back up?😑

YES, you are being curious.

> Only thing that bothers me is how the devs could not figure how to get openkore to work but some people can.
> 
> I'm thinking that they already made a working one but doesn't want to release it

But then you were thinking (accusing) they had working version and keep it to themselves.
YES, this is ACCUSATION. _(Btw, why you think they keep for themselves if they give free for other sever? To help RO rebuild by being ANTI-Bot for pRO? To dev you were asking for help, do they even play pRO? If I were dev, who don't even play pRO, even if I have working one, why would I bother keeping it? No glory or money I get from doing that.)_

![untitled](https://user-images.githubusercontent.com/32188494/31338094-99977ccc-ad30-11e7-9d53-bdfcd16f2cae.png)

BOTHERS (disturbing you) is a complain. This what make you sound ungrateful.

For a FREE STUFF bothering you? If you give your IPHONE 8 to your friend for free and then they said "Why you didn't give me more memory card" "I think you have bigger memory cards but you keep it to yourself and those wireless earphone too. And your mac book to."

How would you feel?
Hope this ENLIGHTEN you why people think you were being ungrateful.
Next time, mind your words. I do understand you but yea, people are vary.😁 😁 😁

**Comment by yakisoba2009** [comment]
@fadreus 
1. Given the circumstance that there is a demand but there isn't much supply, yes it would be profitable. We are talking about the Philippine market right NOW, not before when bot were easily accesible and servers easily bypassed. But there is an exception see #2
2. #1 is only attainable if there  is a possibility to lock a program securely since that's what they do with the pixe bots, but this I admittedly don't have much idea. And yes, it does make me curious.
3. Pertaining to the number of devs and distribution of payment, I might have underestimated the work if it really takes 37 devs to work on a single server of ragnarok? I thought it would only take 3-5 devs at most.
4. Bothered for me meant that I was simply confused why nothing was released even a paid version.
5. Accusation is such a strong word, I was merely assuming hence the word thinking. I made this assumption due to the fact that I saw a legit video of someone using an openkore to roPH.

But most of all, I came here not to start a fight or to whine but mostly to feed my curiosities and find answers. If I have have offended anyone, then I apologize since that was not my intention. No need to get all riled up.

**Comment by fadreus** [comment]
@yakisoba2009  Welp, people.. 🤣🤣🤣
Generally speak, most people thought the way I mention there _(deleted)_ 😂😂😂
People get offended easily. At my 2nd comment _(deleted)_ was suppose to be a joke, but then it get all tense up 😌. Since you might not realize the way you comment there is a little bit in sensitive form and spark misunderstanding, I thought I could clear things up. Hahahaha.. 😌
_(But I always write more than I should_ 😕😕😕)


## Let's just stop talking about this everyone and focus on the issue. 
🤣🤣🤣
![funny-pictures-trying-not-to-offend-anybody-2017](https://user-images.githubusercontent.com/32188494/31347882-71dbe0f4-ad50-11e7-80f2-bcff51885240.jpg)

**Comment by jonelle1990** [comment]
hahahahah cant bypass the BEM in ROPH? hahahahaha. FYI  im not using BEM in ROPH no need to bypass the game :D like i said i have my own program and its easy to use so dont angry with me kid cause i got a working bot in ROPH. /e4

**Comment by jonelle1990** [comment]
and no need to argue with you @bebox123  i have my working bot HAHAHAHAHA

**Comment by boaterszxc** [comment]
stupid jonnel using zumbot i know who made that program stop saying "MY OWN PROGRAM" idiot.

**Comment by alisonrag** [comment]
@yakisoba2009 
there is no one developer playing in phRO, so until appears someone, we need to wait patiently

**Comment by boaterszxc** [comment]
I already had. It's working! But the problem is it has timer on the pcmac.dll

**Comment by alphonse9** [comment]
cool story bro

    On Tuesday, October 10, 2017, 12:09:44 AM GMT+3, boaterszxc <notifications@github.com> wrote:  
 
 
I already had. It's working! But the problem is it has timer on the pcmac.dll

**Comment by voltemir** [comment]
@alisonrag One question, what is wrong with pRO why it is difficult make it work compared to Re:Start?

**Comment by alisonrag** [comment]
@voltemir 
i dont know maybe encrypted packet

**Comment by jonelle1990** [comment]
oopppsss sorry for the term but i got a working bot in roph stupid @boaterszxc hahahahah

**Comment by mhakulit** [comment]
@jonelle1990 share your blessings 😁😁

**Comment by voltemir** [comment]
@alisonrag isn't it the same issue with Re:Start from the last major update wherein openkore temporarily cant connect few weeks ago?

**Comment by alisonrag** [comment]
@voltemir 
nope, the only thing that iRo implemented are the cryptkeys and shuffle packets like in bRO and other official servers, because of this the update come so fast

**Comment by chongtabs** [comment]
other people have and its working.. but we still searching somefixes

**Comment by dellio** [comment]
Hi there guys, I have a friend who bought a bot program I dunno where he bought it.

I ask him to resell the program but he said that he can't because the seller said that they can detect it if he sell it to others.

Is it posible to do detect it?

Hmmph... What do you think guys?

Or maybe the program has a keylogger?

**Comment by Nipodemos** [comment]
# FIRST OF ALL, NO ONE SHOULD SELL OPENKORE

Openkore it's a free, open source program, so no one would ever need to buy , and i do not support this.
second, the only way of he detects is if he put some third party plugin/program inside openkore that is watching every user that buys from him, which means this can be dangerous! he can have the username and password of your account without you know it, so be very careful

**Comment by dellio** [comment]
Woooh, Thank you for that info @Nipodemos, hmmphh i'm also wondering that as my friend said when the bot program is on he can't open a new patch client that makes him to open on another pc.

I should share this to him for his safety.

**Comment by chongtabs** [comment]
Hi still dont have update? please share your config to us it will help a lot.. thanks!

**Comment by voltemir** [comment]
@alisonrag I think it's safe to declare that pRO is not botable at all?

**Comment by fadreus** [comment]
It's bot-able afaik but it's safe to declare that no developers in this community interested in pRO.
Even if there are some interested, it's for sell; ain't free.

**Comment by xDeen** [comment]
I managed to Inject the NETDIRECT.dll on my ragnarok client and login and select character on my account by using my old packets .. after that there are lots of Unknown Packets... but I tried using PEEK and managed to get a new packets (maybe) and update the recvpackets.txt from openkore.. now I can login on my account but I cannot select any character.. it's like there is something that ROExe uses to disallow login.

**Comment by wewet1233** [comment]
anyone here have the full config :D

**Comment by rdaveligon1** [comment]
Can someone help me about this "stuck during route" in my openkore. please see attached file for your reference.


![1](https://user-images.githubusercontent.com/34471188/33872597-6ca56522-df52-11e7-970e-2f6888a9e95b.png)
![2](https://user-images.githubusercontent.com/34471188/33872598-6cea6636-df52-11e7-9651-0b1c43781c10.png)

**Comment by kenneth543** [comment]
my problem here is pcmac.dll and pcmacx.dll the message shown need to update your bot!

**Comment by imthemenace** [comment]
any update?

**Comment by sucubuset22** [comment]
@rdaveligon1 how did even pass the Timeout on account server bro? is that phRO?

**Comment by drewm1983** [comment]
any one have bot in ragnarok philippines? thanks

**Comment by alisonrag** [comment]
continue in #2963
