### ISSUE TITLE
Heal/Support Priest Bot

### ISSUE THREAD

**Issue by WildThot** [OpenKore/openkore#1275]
###### Expected Behavior:

Normal bless, agi & heal + party buffs and following the set target.

###### Actual Behavior:

Found my master!
Packet Parser: Unknown switch: 0AB8
You are casting Blessing on yourself (Delay: 0ms)
You are again: Blessing (Duration: 240s)
You use Blessing on yourself (Lv: 10)
Packet Parser: Unknown switch: 0AB8
You are casting Blessing on yourself (Delay: 0ms)
You are again: Blessing (Duration: 240s)
You use Blessing on yourself (Lv: 10)
Packet Parser: Unknown switch: 0AB8
You are casting Blessing on yourself (Delay: 0ms)
You are again: Blessing (Duration: 240s)
You use Blessing on yourself (Lv: 10)
Packet Parser: Unknown switch: 0AB8
Packet Parser: Unknown switch: 0AB8
You are casting Blessing on yourself (Delay: 0ms)
You are again: Blessing (Duration: 240s)
You use Blessing on yourself (Lv: 10)
You are now: Sitting
You are sitting.
You are no longer: Sitting
You are standing.
You are casting Increase AGI on yourself (Delay: 331ms)
You are again: Increase AGI (Duration: 240s)
You use Increase AGI on yourself (Lv: 10)
You are now: EFST_POSTDELAY (Duration: 1s)
You are now: Sitting
You are sitting.
You are no longer: EFST_POSTDELAY
You are no longer: Sitting
You are standing.
You are casting Blessing on yourself (Delay: 0ms)
You are again: Blessing (Duration: 240s)
You use Blessing on yourself (Lv: 10)
You are now: Sitting
You are sitting.
Disconnecting (numbers)...disconnected
Error: Out of sync with server

It runs from the master even though the master is within a few cells (and moving) half way across the map then returns to continuously bless itself, I have tried looking for alternative threads and found nothing at all similar.

**Comment by alisonrag** [comment]
post your blessing config

**Comment by iamtonysoft** [comment]
i experience the same with my party master-slave but never got the disconnected issue it just wont use the skill to target player. 

#1272 and #1154 dunno if its related to the latest merge. 

**Here is my sample config**
```
partySkill Heal {
	lvl 10
	sp > 10%
	target Player1
	target_hp < 80%
}
```

```
partySkill Increase AGI {
	lvl 10
	sp > 45
	target Player1
	target_whenStatusInactive Increase AGI
	timeout 120
}
```

**Comment by WildThot** [comment]
I have tried several....

> useSelf_skill Blessing {
   lvl 10
   whenStatusInactive Blessing
   sp > 10%
   timeout 5
}

> 

> partySkill Blessing {
    lvl 10
    sp > 10
    notWhileSitting 1
    target_whenStatusInactive Blessing
    target_timeout 240
    timeout 240

}>

but still the issue is... it worked perfectly fine 2-3 weeks ago and since a fresh install the heal slave no longer buffs or heals the master :(

**Comment by iamtonysoft** [comment]
@WildThot 

On my case the priest still heal/buffs himself but never the master. For now all we can do is wait.

**Comment by fadreus** [comment]
I have the same issue after updating src folder.
Planning on reverting back later if it really annoys me.
My temporary solution is using `doCommand` as replacement for `useSelf_skill`
And macro for other stuff.

Not sure if it related to latest update too or not but sometimes monsters is lost before they're dead and some monster still exist in kore while already long gone in game.

*Since I was solo-ing, teleport solve the loop casting. and other stuff. & I can't remember what else.

**Comment by fadreus** [comment]
I have same issue after updating src folder.
Another issue with latest `src` updates are:

- Monster are lost `Target lost` before they are confirmed dead `Target died`.

- Unable to cast skill on target after 3 tries due to monster exist in kore while in game it's already long gone.

After I revering back to previous version it's working fine.
Anyone who want quick solution can use `src` previous version while waiting for solution (Updates from before 2 days ago still fine).
