### ISSUE TITLE
Defend priest first

### ISSUE THREAD

**Issue by kumulo123** [OpenKore/openkore#1278]
Hi is there a way to make the bot attack the monsters that are attacking the priest before the monsters that are attacking the bot himself ?
In other words to defend the slave priest before himself ?
Thanks :)

**Comment by Nipodemos** [comment]
the only way is setting attackAuto to 0 and attackAuto_party to 2

at least the only way i know

**Comment by bllamy** [comment]
attackAuto 1
attackAuto_party 2

party takes priority

**Comment by fadreus** [comment]
There is a way, but not very elegant 🤣.

<details>
<summary>Try this? LOL</summary>
You can try use macro.🤣
When ever your slave got attacked, make a signal to trigger your master macro to change attackAuto from 2 > 1 & after target died change back to attackAuto 2 same with attackAuto_party.

If using macro there is time when some weird thing happens and for backup, use doCommand to change attackAuto 2 periodically (e.g. timeout 600 etc etc) with certain onAction sequence.

Or try make your priest as master, and your DPS as slave. Set your dps slave attackAuto 1 and attackAuto_followTarget 1 while your priest attackAuto is 1 (can use with combination of mon_control.txt all 3 (provoke) for your priest).

These setting will surely kill anything that disturb your girlfriend 😆
The only problem is your priest might attacking monster too slow since it need taking care of others before attacking any monster. But if you are at map full with aggressive monsters, this wouldn't an issue since it gonna attack your party anyway (or other problem is KS 😂😂)
</details>

**Comment by alisonrag** [comment]
any update?

**Comment by plsdontkilme** [comment]
kumulo123 can u give me copy of ur bot?

**Comment by alisonrag** [comment]
use this:
https://gist.github.com/allanon/492cd72bfdd774acdefb821700739ff5

**Comment by kumulo123** [comment]
Thanks i will test when i go back home !!
