### ISSUE TITLE
pls help how to make bot avoid portal

### ISSUE THREAD

**Issue by Queroz** [OpenKore/openkore#1355]
my bot always walk to the portal and i must spend 1 key everyone hour
can anybody help me?
bot location : Alde_dun04
Monster : Bathory

**Comment by alisonrag** [comment]
what portal do you have screen?

**Comment by sctnightcore** [comment]
## Please use the issue template, please post infornations about the server and your configuration.
control/config.txt
**route_escape_reachedNoPortal**

control/mon_control.txt
**Syntax: <monster> <attack> <teleport> <search> <skillcancel> <lv> <joblv> <hp> <sp> <weight>**

**Comment by fadreus** [comment]
Since your question is vague,  here are some answer which you can find using google or with IQ good enough to read at openkore wiki _(just like any kindergarten kid could do)_
### If your request is "make bot avoid portal"
![image](https://user-images.githubusercontent.com/32188494/32401983-bb7fe2aa-c155-11e7-9a4d-5b99c8f17a49.png)

### If your issue is "bot always walk to the portal"
![image](https://user-images.githubusercontent.com/32188494/32401987-d617f828-c155-11e7-9c61-448353ef7581.png)

### If you don't want use specific portal, remove portals from table/portals.txt and set in `config` not to record portal
![image](https://user-images.githubusercontent.com/32188494/32402013-3c8f9516-c156-11e7-928c-c20b0b4b8cce.png)

### or use `routeweight.txt`
![image](https://user-images.githubusercontent.com/32188494/32402047-cd47fce2-c156-11e7-8c53-16226c9ade50.png)

I doubt anyone here would know:
- Who you are
- What server you are playing
- What configuration you are using

Since you are asking "generally" you only get "general" answer.
No one here sleep in same bed with you, knowing everything what you meant.

**Comment by sctnightcore** [comment]
@fadreus  good job ♥
