### ISSUE TITLE
iRO Re:start cant create party

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#1424]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 

when I tried to create a party via command like: party create "anything" it says:

![sin titulo](https://user-images.githubusercontent.com/19712343/33036419-1137c550-ce0d-11e7-9faf-5d1bf606b5b9.jpg)

When practically im not in a party.
Already im using the latest openkore (i downloaded it just minutes ago)

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
```
party create scttttmgtgt
คุณได้เข้าร่วมปาร์ตี้ 'scttttmgtgt' แล้ว
ปาร์ตี้ EXP ได้ถูกตั้งให้ได้เป็นรายบุคคล
```
I can party it.
You should check it out.
1.Repeat name
2.You are still in the party.

**Comment by fadreus** [comment]
@Zelecktor If using latest version, when not in party using console command party will not print that information. You sure you have latest one? Similar issue exist after cmdParty review PR but already fixed.

![image](https://user-images.githubusercontent.com/32188494/33052225-cefba886-cea8-11e7-83fe-c10ca1af5bc6.png)

bRo & iRO already tested with no problem. Which server are you playing?
_**Please use bug report template properly and post your server information and configuration too**._

**Comment by adraaawr** [comment]
@Zelecktor , #1409 fix this, also #1413 to prevent party loss info

**Comment by Zelecktor** [comment]
Fixed!
I downloaded today and they change some lines on the src.
Just update

**Comment by fadreus** [comment]
> (i downloaded it just minutes ago)

> I downloaded today and they change some lines on the src.

cmdParty merged to master 7 days ago.
Autovivification merged 3 days ago.
Party loss info merged 2 days ago.
Your issue 21 hours ago. (not even 1 day)

- Downloaded just a minutes ago, less 22 hours ago.
- Downloaded today, changed some files; before 22 hours ago, latest PR merged 2 days ago. Nothing changed ever since (except unrelated to party, PR from 3 hours ago, and you reply 2 hours ago, assumed downloaded new 2~4 hours ago.

You not Nobita, aren't you? Using time machine from Doreamon before 3 days ago to this time?
It's better not to fabricate facts (lie).

**Comment by fadreus** [comment]
> (i downloaded it just minutes ago)

> I downloaded today and they change some lines on the src.

cmdParty merged to master 7 days ago.
Autovivification merged 3 days ago.
Party loss info merged 2 days ago.
Your issue 21 hours ago. (not even 1 day)

- Downloaded just a minutes ago, less 22 hours ago.
- Downloaded today, changed some files; before 22 hours ago, latest PR merged 2 days ago. Nothing changed ever since (except unrelated to party, PR from 3 hours ago, and you reply 2 hours ago, assumed downloaded new 2~4 hours ago.

@Zelecktor You not Nobita, aren't you? Using time machine from Doreamon before 3 days ago to this time?
It's better not to fabricate facts (lie).

**Comment by sctnightcore** [comment]
ROFL @fadreus
