### ISSUE TITLE
About TalkNPC stuck

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#1459]
Servers: iRO , Restart (meby all ?)
WX using, plugins: macro , eventMacro

When talking to the NPC using macro or eventMacro there is a chance to get stuck.

![1](https://user-images.githubusercontent.com/20753532/33397245-2738a97c-d55c-11e7-830c-57be403b5ca6.jpg)

If using command "talk no" , i get message: _you do no talking with NPC_ . But in fact the conversation goes on and the bot can not move.
The conversation does not end, if i change the map or using command "relog".
It would be good to fix this problem because with a large number of instructions "talkNPC" the bot almost always gets stuck.

**Is necessary to force to end the conversation when you disconnect**

![2](https://user-images.githubusercontent.com/20753532/33397640-4cd5e7c0-d55d-11e7-8f83-5df69b42c0fc.jpg)

Thank you for understanding

**Comment by fadreus** [comment]
Use `ai clear` whenever map loaded? Worked for me all the time. 😁
I override my AI to avoid conflict with long npc conversation.

**Comment by Glikadin** [comment]
In this case the current macro will be aborted =\

**Comment by fadreus** [comment]
Well, in my case, even if NPC sequence cleared after reconnected, the current macro conversation is interrupted. Without completing task before disconnected, the rest of the macro would be useless.
So I re-run macro after relog to tackle this issue before.

**Comment by Glikadin** [comment]
Oh , okay I'll just keep manually restarting all  my macro logic

**Comment by fadreus** [comment]
I use something like this

```
automacro Resume {
console /You are now in the game/
timeout 1
call {
do eventMacro TalkNpc
}
}
```

I used few 'switches' before. After each task completed, other automacro is enabled incase of DC and disabled once the task completed.

I used both macro.pl and eventMacro.pl since I can have both run at the same time without any conflict with one another. Most common use is macro cancel eventMacro or eventMacro cancel macro from continue running and resume it. 😆

Now that I've refined my script so I ditch this kind of 'backup' script.
Only when my connection is poor i use this kind of script again.
