### ISSUE TITLE
Timeout Server Problem again Almost weekly

### ISSUE THREAD

**Issue by HorrendousVon** [OpenKore/openkore#1812]
Hello.. I'm new so I need help and someone to teach me how to auto update my openkore or how to resolve the timeout server problem.. it happens almost weekly after maintainance.. I know allanon must be bussy and I'm shy to bother him every after maintainance.. anyone knows how to solve this? thankyouuuu

 iRO renewal Chaos..

**Comment by sctnightcore** [comment]
download new openkore :p

**Comment by HorrendousVon** [comment]
downloading new openkore wont work i think.. since its the rev packets and sync txt etc i think need to be updated almost weekly.. and since there is no update yet we will only be downloading unupdated codes or program i don't know the terms but i think its in rev pack and syncs which are being changed almost every maintainance

**Comment by fadreus** [comment]
> someone to teach me how to auto update my openkore

Use Git Desktop / TortoiseSVN or Git. You still need to manually click your mouse to update or create schedule task if you using Windows. If you want fully automated, I suggest using Weed or some Beer.

> downloading new openkore wont work i think

Test first before making an assumption. Don't just sit there, twiddling your thumb thinking what will work and what doesn't. Seriously, do you even try?

> since there is no update yet we will only be downloading unupdated codes or program

IRO don't have update since last Thursday and Openkore updated for IRO Renewal last Thursday.
Just to make sure, are you Nobita using Doreamon Time Machine came from last 4 days?

> Hello.. I'm new

I don't know what with you guys "Newbie" attitude.
You guys are lacking effort. All question already been answered again & again. Those discussion are made for public or do you suggest we wrote a letter for each person individually, wrapping nicely with ribbon, apply some perfume and send it in your marry to your doorstep with marching ban walking in red carpet?

**Comment by fadreus** [comment]
> someone to teach me how to auto update my openkore

Use Git Desktop / TortoiseSVN or Git. You still need to manually click your mouse to update or create schedule task if you using Windows. If you want fully automated, I suggest using Weed or some Beer.

> downloading new openkore wont work i think

Test first before making an assumption. Don't just sit there, twiddling your thumb thinking what will work and what doesn't. Seriously, do you even try?

> since there is no update yet we will only be downloading unupdated codes or program

IRO don't have update since last Thursday and Openkore updated for IRO Renewal last Thursday.
Just to make sure, are you Nobita using Doreamon Time Machine came from last 4 days?

> Hello.. I'm new

I don't know what with you guys "Newbie" attitude.
You guys are lacking effort. All question already been answered again & again. Those discussion are made for public or do you suggest we wrote a letter for each person individually, wrapping nicely with ribbon, apply some perfume and send it in your marry to your doorstep with marching band walking in red carpet?

**Comment by fadreus** [comment]
> someone to teach me how to auto update my openkore

Use Git Desktop / TortoiseSVN or Git. You still need to manually click your mouse to update or create schedule task if you using Windows. If you want fully automated, I suggest using Weed or some Beer.

> downloading new openkore wont work i think

Test first before making an assumption. Don't just sit there, twiddling your thumb thinking what will work and what doesn't. Seriously, do you even try?

> since there is no update yet we will only be downloading unupdated codes or program

IRO don't have update since last Thursday and Openkore updated for IRO Renewal last Thursday.
Just to make sure, are you Nobita using Doreamon Time Machine came from last 4 days?

> Hello.. I'm new

I don't know what with you guys "Newbie" attitude.
You guys are lacking effort. All question already been answered again & again. Those discussion are made for public or do you suggest we wrote a letter for each person individually, wrapping nicely with ribbon, apply some perfume and send it in your marry to your doorstep with marching band walking on red carpet?

**Comment by alisonrag** [comment]
@allanon =]

**Comment by alisonrag** [comment]
here wait for the update

**Comment by fadreus** [comment]
Chaos renewal is working fine.
That guy is Nobita, he use Doreamon Time Machine from last Thursday.

**Comment by Nipodemos** [comment]
haahah
is exactly what you say, evertytime the game has a maintence, openkroe has to be updated, and only 1 person do that on iRO, you should peacefully wait

we all do

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/36774481-cdf7748e-1c90-11e8-86b1-23747b459ccb.png)
new openkore 
work :p

**Comment by HorrendousVon** [comment]
thankyou guys..
