### ISSUE TITLE
Timeout on map server (RO:Restart)

### ISSUE THREAD

**Issue by Avngl** [OpenKore/openkore#1887]
Hello. Happened a few hours ago. OpenKore isn't able to connect to RO:Restart with the message "Timeout on map server". I tried downloading the updated OpenKore (Last update, 3 hrs ago) but the error remains.

![image](https://user-images.githubusercontent.com/36796461/38066413-6bb34b02-333a-11e8-973b-0c3393087fb0.png)

**Comment by sctnightcore** [comment]
```
Things to know
Before submitting an issue, ensure you are running the latest commit on branch.
Check if an issue already exists for your request.
Please post in English if possible.
Please use the issue template, please post information about the server and your configuration.
Remember, developers are doing this on free time.
```

**Comment by pampam02** [comment]
i have no idea, but still cant connect,, thanks anyways

**Comment by Avngl** [comment]
Why did you close this?

Anyway, tried the latest commit (41 mins ago) and the issue is still present.

**Comment by Avngl** [comment]
@sctnightcore

**Comment by holoc** [comment]
@Avngl Probably b/c you didn't follow this? 

> Please use the issue template, please post information about the server and your configuration.

**Comment by Avngl** [comment]
@holoc 

Thanks.. But there are posts which are not closed yet they don't follow the template. 

EG: https://github.com/OpenKore/openkore/issues/1882

**Comment by pampam02** [comment]
They probably cant fix this,, lol they dont want issues posted,, 2x lol 
Peace guys,, 
But i do hope you can fix this

**Comment by sctnightcore** [comment]
¯\_(ツ)_/¯

**Comment by Pachu1985** [comment]
whats the rush? just wait...

**Comment by plsdontkilme** [comment]
guys just wait for the update...they doing the update for free...just be patient...

**Comment by Fadreus** [comment]
**For newbies who don't really like to read and fail high school because lazy to read and work at McDonald:**

For official servers _(which is working)_ every time having connectivity issue, you don't have to start new issue. Dev who take care of those servers will update it if they have time.
Check github/openkore readme.

IDK if you guys are still kid or a working adult but if you were an adult, how does it feel when you are doing your work and you boss keep telling you to do your routine work which you already know?
If you were a kid, please act like one and do reading.

Just remember everyone here have a life _(unlike you)_. No dev can give immediate solution _(unless it is simple enough even 4 years old baby can solve it like redownload? which sctnightcore already told people again & again)_

@Avngl Although that thread didn't follow the templates but he did provide necessary information _(at least but not quite)_ .

If you wonder why your thread got closed, prolly because it was routine update.
But even if there is any update, allanon have plugin to automatically start a pull request.
You just need to follow up that PR thread.
Plus, your report structure is like messaging your grandma.
Github indeed for reporting & any part in this world, when it come to reporting we have format & procedure to follow _(unless you were a kid below age you don't know all these stuff yet or if you an adult & don't know about it, please be civilized)_
