### ISSUE TITLE
Openkore can not split Monster Mercenaries ,Monsters.

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1890]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:
![image](https://user-images.githubusercontent.com/23263315/38102782-7c70ef98-33ae-11e8-9c84-1f713c3808e4.png)

**Comment by c4c1n6kr3m1** [comment]
if
any differences
between 
normal Monsters's packet and Mercenaries's packet 
ex actor_spawned,actor_exists,actor_connected
i think

**Comment by moneyisgod** [comment]
Following FAQ = Wrong serverType (packet struct);

Friend tip : At least, you'll discover only debugging the server when packet received.
It takes about : 20 minutes.

There are diferences between Monsters and Mercenaries / NPC and Player, because they ID's are diff ?
And i we can see that when packets ID constantly changes, its a problem for Kore.

Just the ID changes, with static data type. Level of Problem = 1
Just the data type changes. Level of Problem = 2
The ID changes,

ID of packet changes, but his data type is static.[base of Rag & Sak] / Level 1 of survivor--
Data type changes constantly.[Sak x Sak & Rag x Rag & Sak x Rag] / Level 2 of survivor--
The ID,data type, changes.[Sake x Rage & Rag x Rag & Sak x Sak] / Level 3 of survivor--

Thinking on this, they created the heartbeat packet.

**Comment by sctnightcore** [comment]
Fixed: PR #2010
