### ISSUE TITLE
TalkNPC instantly stops/closes the action before being able to respond. (pserver)

### ISSUE THREAD

**Issue by Linklyons** [OpenKore/openkore#2011]
[private server]

Summary: Talknpc command comes back with error, saying something along the lines of "additional dialog actions required but conversation has already ended, current step r1"

It does not matter what responses you give it, it automatically closes the conversation before continuing to the first step after the initial click. Leaving you hanging.

Have attempted help on the IRC, only responses were that "everything looks correct, it should be working".

**Comment by Fadreus** [comment]
Let me use my psychic power to read your mind..
Ohhhmmmmmmm..
Oh I see, you try to do that..
And you were wrong.
Do it like this.

**Comment by Fadreus** [comment]
IDK what planet you are from but we here on earth don't have ESPR ability to read mind.
You need to give full details. If you give little details, its fair you get responses like that.

On earth, we used to say "If you want more, you have to give more."

**Comment by Linklyons** [comment]
Don't be an asshole because someone else isn't as adept as you. If you
wanted more information you could have asked for specifics.

**Comment by Fadreus** [comment]
# This bug report form already asked for specific details.
```
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

## ------------------ Bug Report Template ------------------
###### Summary: 

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:

###### Expected Behavior:

###### Actual Behavior:

###### Steps to Reproduce:

## ------------------ Feature Request Template ------------------
###### Summary:

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:

###### Benefits:

###### Drawbacks:

###### Additional Details:
```

http://forums.openkore.com/viewtopic.php?f=6&t=11287
![image](https://user-images.githubusercontent.com/32188494/40388013-eef2dc7c-5e40-11e8-868e-19ed6f8acce1.png)

http://forums.openkore.com/viewtopic.php?f=0&t=129
![image](https://user-images.githubusercontent.com/32188494/40388435-1f93ae5a-5e42-11e8-8193-3570068c867b.png)
![image](https://user-images.githubusercontent.com/32188494/40388120-375a5076-5e41-11e8-9d1b-a9bceb3801b4.png)

## Your checklist.
- [X] Brief description of the problem.
- [ ] What you have done so far.
- [ ] Portion of config/macros/etc changes that is relevant to the problem.
- [ ] Any other useful information: did you recently get patches, any gm announcements, etc.
- [ ] ###### Expected Behavior:
- [ ] ###### Actual Behavior:
- [ ] ###### Steps to Reproduce:
- [ ] Respect other board members no matter their believes or opinions.

https://github.com/OpenKore/openkore
![image](https://user-images.githubusercontent.com/32188494/40388938-826ba144-5e43-11e8-8dee-288f0d3c4afa.png)

Note: Github is used for reporting bugs & feature request. If you need help coz you're not so adaptable with modern Earth technology, use forum or learn some Mystic Art from Dr. Strange.

**Comment by Fadreus** [comment]
# This bug report form already asked for specific details.
```
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

## ------------------ Bug Report Template ------------------
###### Summary: 

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:

###### Expected Behavior:

###### Actual Behavior:

###### Steps to Reproduce:

## ------------------ Feature Request Template ------------------
###### Summary:

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:

###### Benefits:

###### Drawbacks:

###### Additional Details:
```

http://forums.openkore.com/viewtopic.php?f=6&t=11287
![image](https://user-images.githubusercontent.com/32188494/40388013-eef2dc7c-5e40-11e8-868e-19ed6f8acce1.png)

http://forums.openkore.com/viewtopic.php?f=0&t=129
![image](https://user-images.githubusercontent.com/32188494/40388435-1f93ae5a-5e42-11e8-8193-3570068c867b.png)
![image](https://user-images.githubusercontent.com/32188494/40388120-375a5076-5e41-11e8-9d1b-a9bceb3801b4.png)

## Your checklist.
- [X] Brief description of the problem.
- [ ] What you have done so far.
- [ ] Portion of config/macros/etc changes that is relevant to the problem.
- [ ] Any other useful information: did you recently get patches, any gm announcements, etc.
- [ ] ###### Expected Behavior:
- [ ] ###### Actual Behavior:
- [ ] ###### Steps to Reproduce:
- [ ] Respect other board members no matter their believes or opinions.

https://github.com/OpenKore/openkore
![image](https://user-images.githubusercontent.com/32188494/40388938-826ba144-5e43-11e8-8dee-288f0d3c4afa.png)


<details>
<summary>Note: Github is used for reporting bugs & feature request. If you need help coz you're not so adaptable with modern Earth technology, use forum or learn some Mystic Art from Dr. Strange.
😉😉😉</summary>
I may be asshole, but you're just a dick.
Short one, just like how short you wrote.
GG
</details>

**Comment by Nipodemos** [comment]
That answer is the most well made answer for an idiot I have red in my life

You gave him multiple sites and places that proves he is wrong.
I loved it!

**Comment by c4c1n6kr3m1** [comment]
Fadreus will have a shiny future as a debater :laughing:

**Comment by YourNotSmarterThanMeJustMoreExperienced** [comment]
What a rude response. You guys wouldn't get away with speaking people like that in the REAL WORLD. LOL

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/40847833-0af7824a-65f0-11e8-8406-494f75b16aa5.png)
![image](https://user-images.githubusercontent.com/32188494/40847845-0fc9c8f0-65f0-11e8-8fc4-90bd00516b8c.png)

**Comment by alisonrag** [comment]
continue in #1417
