### ISSUE TITLE
Scrambled config after maintenance/re-download

### ISSUE THREAD

**Issue by YourNotSmarterThanMeJustMoreExperienced** [OpenKore/openkore#2026]

**Comment by Monteray-Jack** [comment]
Have you tried downloading it again?
What are you using to open Config? (I use Note Pad++)

Mine is just fine and I just downloaded it, though I cannot connect til someone more educated than me updates it (got a good ol' timeout on map server deal going on)

**Comment by Minabe** [comment]
That's your text editor's fault (notepad?), simply open Wordpad (guessing you're on Windows), copy-paste the content of the file on it, then copy-paste the content back to the notepad and it'll be back to normal (format is the same but notepad tends to scramble things up bc a different text editor was used to create the file). You should simply copy-paste the actual configuration file from the old openkore version to the new one since nothing changes anyway.

The real problem is that they haven't updated the encryption keys for iRO bc of the maintenance and asking for it is taboo... guides don't really cover what really has to be done (beside all of them being super old) and PEEK doesn't seem to work for me (seems i need to use a different file from the ragexe, like a .dll but there are so many and PEEK doesn't just takes them as is...).
