### ISSUE TITLE
Try to teleport when Anubis is nearby

### ISSUE THREAD

**Issue by easywolf** [OpenKore/openkore#2146]
I try to make this happen, when Anubis is nearby, distance < 5 then teleport.

mon_control.txt
Anubis 0 -5 0

but it didn't really work, can anyone tell me why?

**Comment by Fadreus** [comment]
> tell me why?

![image](https://user-images.githubusercontent.com/32188494/42676759-ee7b0e16-86ab-11e8-9288-9f982ebe4f31.png)

Could you elaborate `didn't really work` ?
I believe if you use `Anubis -1 -5` it would work.

Based on your `didn't really work` and your config, I believe you bot try to attack Anubis when it get attacked 1st before reaching the range distance; thus unable to teleport _(& yeah, teleportAuto stuff is not really optimized.)_

**Comment by alisonrag** [comment]
@sctnightcore 
tele-search is for looking for monster when the monster is not in screen

@easywolf 
can you post your config?
dou you use creamy card, teleport skill or fly wing?

have you configured this in your config in teleportauto_* block?

**Comment by easywolf** [comment]
Thanks for everyone's responding. I tried several methods and feel maybe set [Anubis -1 2] is the better idea for now. 
But the problem is it'll only teleport when Anubis try to do dmg on you. I don't know if there's any way that I can set the bot teleport once it detect the Anubis is trying to attack you (both skills and normal attack), not only teleport after he missed several times then ready to do the true dmg. (Sometimes it can teleport before Anubis do the dmg, but it often teleport after he did some dmg, no matter it's from Anubis' skills or normal attack.)

And here's my teleport setting in config. Thanks again for everyone who is trying to help= )

teleportAuto_hp < 40%
teleportAuto_sp 0
teleportAuto_idle 0
teleportAuto_portal 0
teleportAuto_search 0
teleportAuto_minAggressives 6
teleportAuto_minAggressivesInLock 0
teleportAuto_onlyWhenSafe 0
teleportAuto_maxDmg 2500
teleportAuto_maxDmgInLock 0
teleportAuto_deadly 1
teleportAuto_useSkill 1
teleportAuto_useChatCommand
teleportAuto_allPlayers 0
teleportAuto_notPlayers
teleportAuto_atkCount 0
teleportAuto_atkMiss 10
teleportAuto_unstuck 0
teleportAuto_lostTarget 0
teleportAuto_dropTarget 0
teleportAuto_dropTargetKS 0
teleportAuto_attackedWhenSitting 0
teleportAuto_totalDmg 0
teleportAuto_totalDmgInLock 0
teleportAuto_equip_leftAccessory
teleportAuto_equip_rightAccessory
teleportAuto_lostHomunculus
teleportAuto_useItemForRespawn
teleportAuto_item1
teleportAuto_item2

**Comment by Fadreus** [comment]
You set `Anubis -1 2`.
![image](https://user-images.githubusercontent.com/32188494/42704455-6c24ad08-8702-11e8-93a6-3a5e3776a681.png)

> But the problem is it'll only teleport when Anubis try to do dmg on you.

**You order pizza but you dun want pizza?**

############################################################################

> (Sometimes it can teleport before Anubis do the dmg, but it often teleport after he did some dmg, no matter it's from Anubis' skills or normal attack.)

![image](https://user-images.githubusercontent.com/32188494/42704522-b62bb432-8702-11e8-9762-16eea222660a.png)

I think Openkore got no problem.
What you want is Macro.

**Comment by Rangtasitc** [comment]
@easywolf 
If you want openkore to teleport once Anubis is within 5 cells of you character then inside your mon_control.txt  : Anubis -1 -5 0 or Anubis 0 -5 0 should work. 

BUT : 

open your tables folder and open monsters.txt , now find Anubis and check what number it has.
e.g.      1098 Anubis     (this may be different for you as i don't know what server you play on )

Now in your mon_control.txt file insted of (Anubis 0 -5 0)  try using the number 
e.g.  1098 0 -5 0  

I have to do this for mob like Archer Skeleton because Kore reads the name like : 
1016 Archer	Skeleton  and the name wont work.

if all this fails you could always use     Anubis -1 1 0    or     1098 -1 1 0      and kore will teleport as soon as Anubis is on your screen. ( i understand this is probably not what you want but it beats die'ing )

let me know if the number thing works , best of luck..
