### ISSUE TITLE
Can anybody help me with this issue? izlude to iz_dun portal IRO renewal chaos

### ISSUE THREAD

**Issue by haltamimi** [OpenKore/openkore#2347]
## ------------------ Openkore Issues Template ------------------
izlude 197 205 izlu2dun 107 50 150 c r0 but it goes to the right side of izlude map rather than go to the Sailor. Please Help

**Comment by alisonrag** [comment]
http://openkore.com/index.php/Portals.txt

check if dont have any other portals in the file

**Comment by haltamimi** [comment]
thank you I got it!

**Comment by Fadreus** [comment]
Last time I checked, some portals from alberta to expended city is incorrect too.

**Comment by Fadreus** [comment]
Is this even a problem to stay open?

**Comment by Nipodemos** [comment]
almost sure this is still a issue

Cause can be the outdated fields files, i've noticed this for example in prontera where the bot simply can't make a route to the south kafra.

Izlude is one of the most changed maps in ragnarok, maybe that is the problem

**Comment by Fadreus** [comment]
Well, since general portal is used across all servers, custom changes on different servers should be done personally by individuals; is what I think.

And 

> thank you I got it!

He seems to have fix it already.
Unless there is no more old servers, we can update the portals.
And it's not hard to do it, the instruction is inside the file anyway.

**Comment by Nipodemos** [comment]
well, since it is more a portals.txt problem rather than a outdated fields file, then this issue can indeed be closed.
thanks for the tip 🎉
