### ISSUE TITLE
EventMacro route problem

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#2487]
EventMacro code:
```
			do move 60 123 prontera
```
If the coordinate 60,123 is occupied by another player , bot  is endlessly trying to stand on this coordinate.
It lasts 5-10 minutes! This is a big problem, it looks very suspicious to other players.

**Comment by Fadreus** [comment]
@Glikadin 
In wiki it says there
`Run <command>, as if it was entered in OpenKore terminal. Commands are from Console Commands.`
Command was not even part of macro, so it's not issue in macro.

Bot try to move on occupied spot endlesslly is **ancient** stuff.
Its was like that since WW2 :laughing: 

Maybe need some tweak here?
```perl
if ($args_split[3] =~ /^\d+$/) {
		# distance from map x, y
		$dist = $args_split[3];
	}
```
```
		distFromGoal => $dist);
```

Adding range from destination or something? :thinking: 

But I don't like complicated stuff.
For your macro, just make 2 separate trigger.
One for `do move 60 123 prontera`
Other to trigger when `IsInMapAndCoordinate prontera 60 123`

Though I'm don't see why kore keep attempt to move as if it doesn't even moved to designated location when macro does. :thinking:

**Comment by Fadreus** [comment]
@Glikadin 
In wiki it says there
`Run <command>, as if it was entered in OpenKore terminal. Commands are from Console Commands.`
Command was not even part of macro, so it's not issue in macro.

Bot try to move on occupied spot endlesslly is **ancient** stuff.
Its was like that since WW2 :laughing: 

Maybe need some tweak here?
```perl
if ($args_split[3] =~ /^\d+$/) {
		# distance from map x, y
		$dist = $args_split[3];
	}
```
```
		distFromGoal => $dist);
```

Adding range from destination or something? :thinking: 

But I don't like complicated stuff.
For your macro, just make 3 separate macro.
One for `do move 60 123 prontera`
One to trigger when `IsInMapAndCoordinate prontera 60 123`
One automacro which locked but released by trigger above.
It's not fancy code but it works.

Though I'm don't see why kore keep attempt to move as if it doesn't even moved to designated location when macro does. :thinking:

**Comment by Fadreus** [comment]
@Glikadin 
In wiki it says there
`Run <command>, as if it was entered in OpenKore terminal. Commands are from Console Commands.`
Command was not even part of macro, so it's not issue in macro.

Bot try to move on occupied spot endlesslly is **ancient** stuff.
Its was like that since WW2 :laughing: 

Maybe need some tweak here?
```perl
if ($args_split[3] =~ /^\d+$/) {
		# distance from map x, y
		$dist = $args_split[3];
	}
```
```
		distFromGoal => $dist);
```

Adding range from destination or something? :thinking: 

But I don't like complicated stuff.
For your macro, just make 3 separate macro.
One for `do move 60 123 prontera`
One to trigger when `IsInMapAndCoordinate prontera 60 123`
One automacro which locked but released by trigger above.
It's not fancy code but it works.

I don't see why kore keep attempt to move as if it doesn't even moved to designated location when macro does. :thinking:

**Comment by Glikadin** [comment]
Thanks for answers! I will try to fix with the problem
