### ISSUE TITLE
Iro

### ISSUE THREAD

**Issue by claudio17** [OpenKore/openkore#2515]
Hello
iro update plz

**Comment by Fadreus** [comment]
Read please.
God bestowed you 1 brain and 2 pair of eyes.
Don't want to use it, please donate to research facilities.

**Comment by claudio17** [comment]
Do I have to read men?

**Comment by Fadreus** [comment]
Yes, because weekly update doesn't to be told and you don't have to ask.
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers
You just make a mess in this place, making it harder for future reference on thread issue for anyone else.
Github is a working place, not a weechat, facebook or any kind of social media.

You've been told before posting an issue what to be done but you deleted it, you ignore it.
![image](https://user-images.githubusercontent.com/32188494/48927053-ec210380-ef0d-11e8-8d50-2a78c9bdd0f6.png)
The instruction required you to use LATEST VERSION and use BUG REPORT TEMPLATE before issuing.

We here are civilized community.
We have SOP to make troubleshooting easier.
Making it easier for users and developers.
If you just want to ask, use IRC.
If you want to discuss something, use forum.

Everything have been clearly stated in the front page of this repo.
Don't make your ignorant hindrance to others.
This is why we can't have good stuff.
