### ISSUE TITLE
Vending open buy shop bot configuration

### ISSUE THREAD

**Issue by silentkiller123** [OpenKore/openkore#254]
Hey folks i dunno if its the correct place to request this.
Close the thread if i am not allowed to request
But i wanted to know if you guys could share configuration for opening buy shop in iro server 
Buy shop as in a shop to bulk buy  materials for foods and stuff like a vending bot

Thanks and Cheers :D

**Comment by Cozzie** [comment]
Have you tried to look at the manual?

**Comment by silentkiller123** [comment]
yes sir i have refer it.
I am not well versed with coding . 
Hence i needed help

**Comment by ChrstphrR** [comment]
Looks like the manual has nothing of note regarding Buying shops -- it can be found hunting in the forums,  @silentkiller123 

Looks like this needs to be remedied by adding this information into the wiki.
I will review what info is in place for the normal vending shops in the wiki, and try to add the appropriate info for Buying shops.   Or, add the necessary info for both Buying and Selling shops to the wiki.

What I did find regarding buying shops:
[http://forums.openkore.com/viewtopic.php?f=16&t=210059](url) 

It does look like it works slightly differently to set up a buying shop than the normal sell shop, so this does need clear documentation.

**Comment by nizdi** [comment]
Any update on this issue? Because in that forum link I was the one saying to do not download the plugin the OP forum since it had some shady code to send username:password to some server, I'm not really sure now since it's been a long time. But I tried today find info's about how to make a a Buying Shop and could not find.

What I found is that some commands in /src/Commands.pm like closebuyshop and buyer are not in the wiki. Also, I could not find which file would teach me how to adjust config.txt so I could open a buying shop.

Another issue, but I cant make a new thread for this: Command buyer (it's not in the wiki, but i guessed from vender (vl --> vender; bl --> buyer) is making me disconnect. Any shop, anywhere.

**Comment by Fadreus** [comment]
Been looking into this too for quite a long time ago.

But as for command `bl` making it disconnect,

![image](https://user-images.githubusercontent.com/32188494/37750424-df45421e-2dc7-11e8-8466-4f36af8bbf71.png)

<details>
<summary>I tried in IRO and it's fine. No Disconnection.</summary>

_Yeah, the documentations are missing at wiki and commanddiscription.txt._

</details>

**Comment by c4c1n6kr3m1** [comment]
@nizdi
in what basis u said the plugin buyeropen.pl  send username?
i never use the code, but i remember grab the plugin, and i don't see any suspicious code

about the command "buyer" 
i'm too lazy to fix it now, but the logic on the command is wrong because try to use the same logic buying from "vendor"
so u will dc if using it

**Comment by nizdi** [comment]
@c4c1n6kr3m1 
I dont mean any buyeropen.pl, I'm talking about exactaly this plugin that was in this url http://forums.openkore.com/viewtopic.php?f=16&t=210059. It's not even possible to download, if  you have the old download from this same url you can see what i'm talking about. Even one of the developers from forum agreed with me, since there was no reason for the plugin to use password from config.txt.

**Comment by c4c1n6kr3m1** [comment]
that's the plugin name dude
pretty sure it has been removed because of your report
and i'm pretty sure the one i've seen is the the same plugin

# Plugins buyeropen V.1.0 by Darksammee
# username in Forums Openkore : yuranansam
# email : yuranan_sin@hotmail.com && darksam@admin.in.th
#
#==[ How to Set Up Open Buying Store ]==
#
#-- config.txt
#
#BuyingStore < 0=Off | 1= On >
#BuyingStore_title <shop Name>
#
#
#-- buyingstore.txt
#**One item per line.
#
#<item name><TAB><Price><TAB><Amount>
#
#Example: Rough Oridecon	5000	1
#
#
###################################################################

**Comment by nizdi** [comment]
That's what I'm saying neither you nor me have the same file from the url I gave you. It's my word against yours. You can't prove it didn't had a file called "proxy" using user:password from config.txt and I can't prove either. An developer from forum was in the same side as me since the file was suspcious. My report was only to wait to download before someone with more knowledge, if the person who removed agreed with my report it's not my fault.

Show me **same** file it was there and we'll solve this. You can't ask for my reason to report if all you have is   belief that was the same plugin. I did my work as a user to alert others, I'm sorry I was not administrator/moderator at time to delete or even backup the file. That time we were having a lot of brazilian forums uploading openkore folders with keyloggers/macros that steal password . Maybe if that was the case from the link I sent, and I was 100% sure about this (remember I did not said it was a keyloggers/some other things, I said to WAIT) I should have let people lose theirs accounts.

It was not normal for a plugin to use Buying Store use somehow user and password from config.txt. What your basis to that happens? I'll tell you I don't know, that's why I reported. I was not the one that deleted it, cause I don't have the knowlodge to do so.

Your only basis is that you are pretty sure you saw the same plugin. My basis is i'm pretty sure there was a file inside using username:password. Give me a reason to this

**Comment by sctnightcore** [comment]
@nizdi read wiki .

**Comment by nizdi** [comment]
@c4c1n6kr3m1 
Only situation I can see: In the rar/zip it was posted in forum contain: src\Network\Send\ServerType0.pm, config.txt, Plugins buyeropen V.1.0 by Darksammee. When I gave it a check I might have confused plugin with servertype0. I doubt that, since as I said in forum there were 3 words I saw: proxy, userid, password. Userid and proxy were not found in that plugin you sent. Also, some of his others posts are suspscious too http://forums.openkore.com/search.php?author_id=31738&sr=posts, that only give me more confidence that I actually found something suspcious in the download link.

I posted in both forums same day, so I think I saw openkorebrasil and went to openkore to check the source. I don't even remeber using this plugin (even posting in topic probaly because i read comments in the plugin) but it looks like it' buggy too but will give it a try later today.

**Comment by c4c1n6kr3m1** [comment]
i can not remember if there is any ServerType0.pm inside the downloaded file
and inside my filder rightnow only left the buyeropen_install.txt and buyeropen.pl

about the plugin
i don't speak brazillian nor english
using google translator, it is said about missing detect login or something
so u can try add something like this under "sub buyingstorestart {"
```return unless (($net->getState() == Network::IN_GAME) && AI::isIdle);```
