### ISSUE TITLE
Help Marco geffenQuest

### ISSUE THREAD

**Issue by AloveraTh** [OpenKore/openkore#2779]
automacro geffenQuest {
exclusive 1
timeout 120
BaseLevel > 0
QuestHuntCompleted 62680
macro_delay 3
call {
    if (&questCompleteCount(62680) == 1) call Petit

    log Quest not Completed yet
    }
}

macro Dargon {

   do conf lockmap gef_fild08
}

macro Petit {
log completed quest of $.param[1]Petit
do is Butterfly Wing
do move geffen 75 79
do talknpc 74 79 c c r1 c r0 c r6 $.param[0] c r0 n
do talknpc 74 79 c c r0 c r6 c $.param[0] c r0 n

}

**Comment by sctnightcore** [comment]
Please use the issue template.

**Comment by Nipodemos** [comment]
and please tell us what you want, what is the problem and what you already tried to solve it

**Comment by Fadreus** [comment]
If we don't stressed out that personal problem shouldn't be posted here rather than openkore problem itself, we gonna get tons of noob question in the future.

Just saying.

& for this non-openkore problem, this problem lies with the eyes of this user, not openkore.

`QuestHuntCompleted 62680` ->> Da fuq?

http://openkore.com/index.php/EventMacro
`QuestHuntCompleted <comma separated list of pairs of quests ID and Mob ID>`

Example:
`QuestHuntCompleted 7122 1002, 7127 1004`

Already written there need quest ID and Monster ID
Still put Just Quest ID & no Monster ID???!!!
![image](https://user-images.githubusercontent.com/32188494/58758853-52897d00-8554-11e9-9242-e7e3ee6a18fc.png)


Already give example.
Need someone put loud speaker shout in your head, is it?
Or need Prime Minister Broadcast announcement on your Region TV network ah?

Siao leh..
Shouldn't post in Github Openkore Repo.
Should go hospital see missing some eye or both eye or not.

**Comment by Fadreus** [comment]
If we don't stressed out that personal problem shouldn't be asked here rather than openkore problem itself, we gonna have tons of noob question in the future.

And this problem lies with the eyes of this user, not openkore.

http://openkore.com/index.php/EventMacro
`QuestHuntCompleted <comma separated list of pairs of quests ID and Mob ID>`
Example:
`QuestHuntCompleted 7122 1002, 7127 1004`

## Already written carefully and nicely there need Quest ID and Monster ID along with simple example & then come this guy who buy a stove and said it have problem coz he didn't use with the gas.
![image](https://user-images.githubusercontent.com/32188494/58758949-9761e380-8555-11e9-805f-7a3971d31c4e.png)

**Comment by Fadreus** [comment]
In fact, he just come to Walmart, bring the stove and put sticker on it "Help stove" then leave.
If I facepalm hard enough, I don't have a face.

Common sense dude.
Common sense.

I understand most people not expert but common sense should come as pre-installed as you download School. Even if you dont go to school it should be have version 1 somewhere when you were sperm and auto update as you grow old.
