### ISSUE TITLE
zeny amount not updating after relog/charselect

### ISSUE THREAD

**Issue by xDuds** [OpenKore/openkore#2788]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

ServeR: bRO
version versionctime:2019_05_31
bug report
The zeny amount is not updating if you spend the zeny on another openkore console or on the official ragnarok client. After relogin or charselect, the amount still shows as if you never spent, unless you do trade with a player or buy/sell with a npc.

**Comment by Fadreus** [comment]
Just restart ur bot.

**Comment by Fadreus** [comment]
Related to this issue
-Base level is not updated if level up with different client.
-EXP is not updated if using exp gained using different client.
*(There are more but I couldn't care less or even remembering it).*

Anyways, I noticed this early 2019.
I thought this was intended but seeing this issue is still open, so I  add few more that related to  this issue.

It appear to me as openkore only update once; when client started or when there are changes rather than updating character data every time logged in. I assume it to reduce the load on openkore/server?

몰라
![FB_IMG_15625044282660696](https://user-images.githubusercontent.com/32188494/61588427-ca2b6e00-abcd-11e9-99c6-8b7d81707450.jpg)

**Comment by moneyisgod** [comment]
Maybe something about not design pattern on 'player' object.
