### ISSUE TITLE
Bot can't go to Bra_dun01

### ISSUE THREAD

**Issue by bookbk** [OpenKore/openkore#2925]
In portal.txt

bra_in01 148 57 bra_in01 31 72 <<< This line should have been deleted, It's made bot walk the wrong direction when it go to dungeon.

bra_in01 144 187 bra_in01 0 206 102 c r0 n <<< This line should have been fixed to "bra_in01 144 187 bra_in01 206 102 c r0 n" because 0 after destination is a amount of money that have to be paid for getting inside.

Moreover after fixed it, Bot still doesn't get through the bra_dun01. It's stuck at NPC "Open manhole". I tried many ways but it didn't work. Maybe someone can have the way to fix it.

**Comment by c4c1n6kr3m1** [comment]
well, i have both portals and working fine
AFAIR, brasilis, bra_in01 maps are not perfect,(maybe outdate field? you can create your own, make sure to delete the older .fld .gz .dist)
else, you probably stuck around bra_in01 13 160, because there are statues there

about the portals
you can delete unused portals , than use command "portals recompile"

and, if you still stuck near the Open manhole (and you will) , create automacro for that

**Comment by Fadreus** [comment]
> bra_in01 144 187 bra_in01 0 206 102

Typo from 5b1af26.
Been 2 years. :rofl:

**Comment by c4c1n6kr3m1** [comment]
my bot 5 years late, so i'm lucky :D

**Comment by bookbk** [comment]
Thank you for all suggestion

Now this is a solution for someone who looking for
First step => Delete the line "**bra_in01 148 57 bra_in01 31 72**" at tables\portal.txt
Second step => fix the line "**bra_in01 144 187 bra_in01 0 206 102 c r0 n**" to "**bra_in01 144 187 bra_in01 206 102 c r0 n**"
and the last step => put **script to eventMacros** at below

> automacro Bra_DunEntrance {
> NpcNear /Open manhole/
> call {
> do talknpc 206 188
> }
> timeout 5
> }

**Comment by bookbk** [comment]
timeout 15 is better if bot have to walk back
