### ISSUE TITLE
Gramps warp to TI

### ISSUE THREAD

**Issue by bookbk** [OpenKore/openkore#2970]
When Bot warp to
Low-TI -> epay_dun00l
Mid-TI -> egef_dun03m
Hi-TI -> I don't know, I haven't been there before.

Bot will stuck on left corner of the map moc_para01

![Capture](https://user-images.githubusercontent.com/31322843/68453673-ddb81e80-0228-11ea-8b71-08ced1ca1ad3.PNG)

To fix it, it have to make change in moc_para01.gat file but still original moc_para01.xpm as they were so the minimap wouldn't fixed.

1. Delete moc_para01.fld.gz out of the folder "field"
2. put 3 files in folder "field"
epay_dun00l.fld
egef_dun03m.fld
moc_para01.fld
3. put file "portal" in folder "table"
4.put moc_para01.xpm in folder "map"

http://www.mediafire.com/folder/pgk5advydk213wh,5dab3679tofxbw1,exhq8aczimw62qn,zsatb1dpn3ilvk2,w8hz2zy997auqod/shared

after doing that Bot can move to TI by typing in command console but can't move by lock map.
it has shown the line of "Invalid map specified for lockMap - map epay_dun00l doesn't exist"

Maybe someone has the way to fix it.

**Comment by alisonrag** [comment]
Did u added the maps in maps.txt?

**Comment by c4c1n6kr3m1** [comment]
and after that , use macro

**Comment by jcbjacob** [comment]
Any openkore work for idro ?

**Comment by bookbk** [comment]
> Did u added the maps in maps.txt?

Could you explain in detail?

Is that mean put map epay_00l.rsw in map.txt of folder iro?

**Comment by c4c1n6kr3m1** [comment]
i 'll tell you what is the problem

normal auto routing using npc, bot always search shortest direct walkable line , with distance is 10
thats why on moc_para01 you'll see the destination is on the left side, although gramp at the middle, that's why you moved to the left side

for iro server , you will stuck
but not other server
why ?

try using iro client and you'll realize that the left part of the desk is unwalkable
so make a macro for it, don't edit the source field if you don't understand

close this one!!!!

**Comment by Fadreus** [comment]
I only remember having this problem when I set `route_avoidWalls 0`.
Tho I usually use macro. :neutral_face:

**Comment by alisonrag** [comment]
this seems like a bRO where unwalkable cells are added near to npc but only in server side, the solution to this is use macro, or use gat editor to add manually these unwalkable cells
