### ISSUE TITLE
Does openkore still run on IRO ?

### ISSUE THREAD

**Issue by jojo801** [OpenKore/openkore#3105]
Yesterday some user from Korea said, NO! 
Please someone verify.

**Comment by Cryptologism** [comment]
Well im also asking the same question tou

**Comment by Fadreus** [comment]
Dear monkeys.
What need to be clarified is if you have brain and eyes or not.
The fucking read me is meant to be read, not a fashion show.
It state there not working.
If a shop put a sign closed, you are idiot to ask people to verify if that shop closed or not.

Dont spam same thread.
Follow the rules, uncivilized ape.
Learn to read.

**Comment by Cryptologism** [comment]
> Dear monkeys.
> What need to be clarified is if you have brain and eyes or not.
> The fucking read me is meant to be read, not a fashion show.
> It state there not working.
> If a shop put a sign closed, you are idiot to ask people to verify if that shop closed or not.
> 
> Dont spam same thread.
> Follow the rules, uncivilized ape.
> Learn to read.

Well that was a obvious answer and very uncivilized answr and maybe.. Maybe you are the ape one.. Why because you are more uncivilized than us and you shown that how low you life is by answer like a b1tch.. And if you dont want to answr just let them be and let the others answer for us. Btw like me im was not play bot for long time and this time im online and i cant believe that i meet the very rude human* ops sory.. It was human(Now an uncivilized ape) answer the questions.

**Comment by Cryptologism** [comment]
> Dear monkeys.
> What need to be clarified is if you have brain and eyes or not.
> The fucking read me is meant to be read, not a fashion show.
> It state there not working.
> If a shop put a sign closed, you are idiot to ask people to verify if that shop closed or not.
> 
> Dont spam same thread.
> Follow the rules, uncivilized ape.
> Learn to read.

Btw.. You are humiliating your self and your country bro. What a shame

**Comment by Fadreus** [comment]
> if you dont want to answr just let them be

https://github.com/openkore/openkore/issues?q=iro
#3103
#3102
#3033

https://github.com/openkore/openkore/issues?q=iro
Already been answered.
If you gonna say that is old, then are you gonna ask if earth still oval shape? Who knows, maybe yesterday it become flat?

> Btw like me im was not play bot for long time

http://forums.openkore.com/viewtopic.php?f=0&t=129
![image](https://user-images.githubusercontent.com/32188494/78549145-7aacd100-7834-11ea-925c-344fd9c5e557.png)

Maybe you haven't been using bot in awhile but **IGNORANCE IS NOT AN EXCUSE.**

![image](https://user-images.githubusercontent.com/32188494/78549451-00c91780-7835-11ea-8579-9a0d6b9203cc.png)

https://github.com/OpenKore/openkore#faq-frequently-asked-questions
![image](https://user-images.githubusercontent.com/32188494/78549880-b005ee80-7835-11ea-8218-a1e909538729.png)

https://github.com/OpenKore/openkore#things-to-know
![image](https://user-images.githubusercontent.com/32188494/78551109-c1e89100-7837-11ea-815e-5e21dda18453.png)


![image](https://user-images.githubusercontent.com/32188494/78550003-e7749b00-7835-11ea-9402-6cef3cb17e19.png)

![image](https://user-images.githubusercontent.com/32188494/78550325-771a4980-7836-11ea-8c70-7f87d0a2812d.png)

https://github.com/OpenKore/openkore

Please state facts rather than opinion.
![image](https://user-images.githubusercontent.com/32188494/78550826-5d2d3680-7837-11ea-9975-9e035f6c6570.png)

**Comment by Cryptologism** [comment]
Well that a good one answer tou. My bad
