### ISSUE TITLE
Dumper does not display information in the WX interface

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3126]
* **Openkore version git**: last
* **Server**: any
* **Bug Report / Feature Request**: Dumper does not display information in the WX interface
* **Summary**:
1. run start.exe and use the command `eval print Data::Dumper::Dumper(%items_control);`:
![изображение](https://user-images.githubusercontent.com/7117363/81235589-fe103c80-9003-11ea-9dcf-ee593bd522f2.png)
2. run wxstart.exe and use the command `eval print Data::Dumper::Dumper(%items_control);`:
![изображение](https://user-images.githubusercontent.com/7117363/81235832-8abafa80-9004-11ea-8186-1f2d00723c51.png)

**Comment by ya4ept** [comment]
workaround: 
`eval Log::warning Data::Dumper::Dumper \%items_control`

**Comment by Nipodemos** [comment]
i noticed this too one day that i was trying to debug. although i have no ideia how to solve this problem.
In the end i did just as you and used `Log::message` or `Log::warning`

**Comment by c4c1n6kr3m1** [comment]
i always use wx on my main char
and long time ago,  i always hate pack 'a' because it broke the message
i use this now
```
eval use Data::Dumper; $Data::Dumper::Useqq = 1; $Data::Dumper::Sortkeys = 1;message Dumper(\$char);
```

**Comment by alisonrag** [comment]
While I was updating the Win32 console I see in the code that the interface create a fake console.
The interface hide the original one and to message appear in fake console need to use writeOutput function that's why Log functions work and print not.
`eval print` is printing in the hide (original) console, while `eval message` is printing in the fake console

Check https://github.com/OpenKore/openkore/blob/69cdfa5ebad07402858140c1cef78744092e7811/src/Interface/Wx.pm#L418

**Comment by alisonrag** [comment]
Win32 interface:
https://github.com/OpenKore/openkore/blob/69cdfa5ebad07402858140c1cef78744092e7811/src/Interface/Win32.pm#L587
