### ISSUE TITLE
Unable to cast skill Storm Gust in 3 tries

### ISSUE THREAD

**Issue by liandy052008** [OpenKore/openkore#3752]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

I have tried about 3 days still i am getting the same error,
i have changed map and monster same error
please help

automacro castSG {
sp > 20
map mjolnir_12
timeout 1.5
run-once 1
call {
do sl 89
pause 0.5
release castSG
}
}

I want to cast my SG on where i am standing, sorry but i still cannot get it, i have read many instructions.

I am using the latest openkore from here github

![edrror](https://user-images.githubusercontent.com/52085930/236285531-a874628e-0b1d-4eb5-93cb-efdc22a0ea76.png)
![errorsg](https://user-images.githubusercontent.com/52085930/236285600-478154e3-95e0-41f8-8c22-053e8c0d21ef.jpg)

**Comment by alisonrag** [comment]
if you are using bot on gepard server this is because of gepard, it don't allow to cast some AoE skills if client did not any action in the last seconds.

as you can see in the image , i got some skill fails, but after click in client and back to openkore to send the skill command gepard shield allow
![image](https://user-images.githubusercontent.com/10372732/236314685-b3942f5b-8591-44b0-ba6a-3dd5f74d1b0f.png)

**Comment by liandy052008** [comment]
yes sir this is on gepard shield server, and as you are saying once i click on the client since it is xkore1 it started to cast then after it will not.
any way to fix this?

**Comment by alisonrag** [comment]
this is not openkore related, openkore send the correct packet, ask to your seller to see if he can do something in bypass
