### ISSUE TITLE
Botting in Unlisted Server

### ISSUE THREAD

**Issue by FujitoraD** [OpenKore/openkore#458]
Hi! Is there anyway to bot using openkore in a server that wasn't listed in choices of servers? Thank you in advance!

**Comment by holoc** [comment]
Refer to the guides under "Starting with OpenKore" > I want to bot on
private servers >
*Did not find your server?* Read the guides:

   - Extracting data from the server
   <http://openkore.com/index.php/Connectivity_Guide>
   - Configuring serverType <http://openkore.com/index.php/ServerType>
   - Extracting recvpackets
   <http://openkore.com/index.php/Packet_Length_Extractor>

**Comment by harley24** [comment]
Holoc.. I'm having a unknown packets like 09DD 09DC etc.. When i use packet extractor like peek master.. There's always a error but i got the packet lenght,packet keys, and random packets. ? Can you teach me how to get and use it properly?.. I used all application of packet extractor.. One send that the exe has protector.. The other error was can't see the exe.

**Comment by holoc** [comment]
@harley24 There's already another thread on this topic. Have you tried everything in [this thread here](https://github.com/OpenKore/openkore/issues/351)? Please don't hijack another thread in order to get an answer. Instead, if you still haven't found an answer, start a thread with a more details (possibly include screenshots) on what you have done so far, and with what Openkore version.

**Comment by harley24** [comment]
I already fixed it.. now my problem is my WPE and wireshark not working well in a server that have gepard.. the WPE didn't register any packets or Ip.. the wireshark can't detect the login packets..
