### ISSUE TITLE
'X' outside of string in unpack at src/Network/Receive.pm line 2041.

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#462]
OpenKore version what-will-become-2.1
@ai_seq = macro
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_02_28
Loaded plugins:
  plugins/alertsound.pl (alertsound; description: plays sounds on certain events)
  plugins/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)

Error message:
'X' outside of string in unpack at src/Network/Receive.pm line 2041.

Stack trace:
'X' outside of string in unpack at src/Network/Receive.pm line 2041.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x469594c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		$msg = substr($spellInfo, $i, 19);
* 		($ID, $sourceID, $x, $y, $type, $range, $fail) = unpack('a4 a4 v3 X3 C2', $msg);

**Comment by ChrstphrR** [comment]
I received this too, wasn't around to see the particulars.

The line in question is part of 

`#09CA
sub area_spell_multiple3 {
`

This was last changed in 8ca404f4e73909f2dd2ab91fa33b62ed9c2935cf  on November 13, 2015.

Did we have a packet change on official servers that effects this?

**Comment by Glikadin** [comment]
This problem arose after I completely updated Openkore for Doram Ubdate on iRo.
Look this screenshot: http://i.piccy.info/i9/a859ca283dbb910e93b5451c51d39c94/1488390397/132993/1124185/bug.jpg
Fix it pls.

**Comment by LoseracK** [comment]
It's simple, you just need to check if the size of this packet is equal to 19. 
Post your recvpackets.

**Comment by LoseracK** [comment]
Look this ! The pack way is to 19 bytes. 
============================================================
https://pastebin.com/zKFpBY63 - here is equal to 18 and 
Do the subtraction x - 4 = 14 length	-> AnkRO
iRO recvpackets = 23 - 4 = 19 length	-> iRO
But iRO is using 09CA -1 23 0
============================================================

But since the code have implemented : 

$msg = substr($spellInfo, $i, 19);
The last prefix and replace by "$len".


It was my conclusion. It's more easy replace such as : 

I've thinked why don't we use : 

'099F' =['area_spell_multiple2', 'v a*', [qw(len spellInfo)]], # -1

replacing 099F by 09CA ? 

Or am i very high ? @itsrachelfish

**Comment by moneyisgod** [comment]
The only change was 👍 in /Receive/ServerType0.pm. @ChrstphrR 
Do you think reversing it will work ?

**Comment by alisonrag** [comment]
maybe the size of 09CA is wrong in recvpackets

someone is getting this error yet?
