### ISSUE TITLE
Encrypted Packet - Version and Master_Version

### ISSUE THREAD

**Issue by Razalka** [OpenKore/openkore#468]
Anyone can help what the Version and the Master_Version if the packet encrypted like this ?
The Grf encrypted also.

![opkore 2](https://cloud.githubusercontent.com/assets/25100730/23541123/01f94a0a-0018-11e7-8b00-2aa82da8b21c.JPG)

Thank you.

**Comment by 2eazy4daliz** [comment]
I got maps.txt must be in utf-8 encoding, anyone know how to fix this?

**Comment by Razalka** [comment]
i think you have to save your maps.txt file in utf-8 encoding.
open your maps.txt and save as it, in the bottom of save as windows, change the encoding to utf-8 and save it with the same name.

**Comment by 2eazy4daliz** [comment]
Thank you sir, you're such a great help for a newbie like me,we need more
people like you around here , hha

**Comment by Razalka** [comment]
> Thank you sir, you're such a great help for a newbie like me,we need more
people like you around here , hha

and now im waiting someone might help my problem hahaha

**Comment by 2eazy4daliz** [comment]
What problem do you have if i may ask?

On Mar 3, 2017 2:31 PM, "Razalka" <notifications@github.com> wrote:

Thank you sir, you're such a great help for a newbie like me,we need more
people like you around here , hha

and now im waiting someone might help my problem hahaha

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenKore/openkore/issues/468#issuecomment-283885817>,
or mute the thread
