### ISSUE TITLE
pRO - Char server connectivity (keeps trying to connect to 127.0.0.1)

### ISSUE THREAD

**Issue by Xinnux** [OpenKore/openkore#556]
As title states, I'm having issue connecting to Philippines RO Valkyrie server. OpenKore keeps trying to connect to 127.0.0.1 (char server) instead of the actual IP address. 
![screen shot 2017-04-18 at 10 39 20 am](https://cloud.githubusercontent.com/assets/27737073/25145224/6afcb0b0-2425-11e7-9b2b-5bb131cc0607.png)

Also, I've tried extracting the ragexe to update the packets but PEEK and other tools skylorD (from OK forum) suggested would not work. Anyone had similar experience?

Thank you in advance

**Comment by markkevinmacadangdang** [comment]
hi bro..just trying to run bot too on Openkore for pRO and i managed to get the ip details by extracting it via packets taken through wireshark... are you able to run the bot program now?

**Comment by imic23** [comment]
hey. what pRO server is this? i would like to play in a pRO server.

**Comment by faststare** [comment]
it's a dead server. pRO is a official philippine ragnarok online back then but the franchisee shut down the said server one or two years ago. but new franchisee will open a new pRO in the philippines where modeled to thaiRO which they called revoClassic (mixed of prerenewal and postrenewal game features). I just don't know it can bypass it by openKore. I will be glad they will add support to new pRO again.

**Comment by rollydavid0303** [comment]
hi been trying to bot on thai server for testing for pRO. looking for support

**Comment by brithannica29** [comment]
I am trying to run the bot to ThaiServer as well as preparation to upcomfing pRo but I'm having an issue to run the bot by myself.

**Comment by faststare** [comment]
@rollydavid0303. openkore is a community-based software. therefore, you will have to wait for some developer to hack/find to the new game guard variant. or find your own solution because no one will support you here but you may contribute with it to improve the software itself.

PS: if you really like playing RO again, just play the game by yourself or develop your own bot. It will enjoy developing your own OpenKore variant than playing shitty game(if you really want to venture on programming). grow up kid. LMAO

**Comment by rollydavid0303** [comment]
@faststare  dude did I asked them to create a bot for me? I asked them helped because Im having a difficulty connecting to the server. They created this forum to helped others on their issues. Its not like I asked them to do all the work for me. Im asking suggestion to resolved the issue. Grow UP dude if you dont want to help just STFU.

**Comment by faststare** [comment]
@rollydavid0303 jut WOW. you are f*cking funny. ignored!
no one will help you with that kind of attitude. you are just full of retard.! :)

**Comment by rollydavid0303** [comment]
@faststare Im rude with people who are rude to me. You started it by saying "Grow up kid". you can just leave or ignore this thread because we dont need people that are so amaze with thereself. You said "because no one will support you here" so whats the point of having a forum? Don't hate nigga.
