### ISSUE TITLE
Random "Could not find an NPC at location: (xxx,xxx)"

### ISSUE THREAD

**Issue by userix** [OpenKore/openkore#592]
I would randomly get "Could not find an NPC at location:(29,207)" when trying to go to cmd_fild03, or sometimes pay_dun01.  If I manually move the character to a far away spot, then the ai will find the warp NPC and continue.

**Comment by ferluk** [comment]
Could not find an NPC at location (134,88). @ izlude town

**Comment by Slipxxliose** [comment]
Post some screenshot. I just believe seeing.

**Comment by fadreus** [comment]
This often caused by position lag (Moving while casting skill, NPC need to remain in `clientSight`) or the npc coordinate in `portals.txt` is incorrect.

Some solutions:
- Use `macro` to relog
- Use `macro` use command north, south, west, east (Determine when it usually happen and reverse few steps back from walking towards npc).
- Use `noInTown 1` in skill configuration.
- Update NPC location in `portals.txt` for route.
