### ISSUE TITLE
New iRO server (Re:Start) config

### ISSUE THREAD

**Issue by jascaldeira** [OpenKore/openkore#641]
can you add a config for this server? thanks

**Comment by DeletsXavier** [comment]
Waiting together.. :)

**Comment by sctnightcore** [comment]
[Ragnarok - Re:Start]
ip 128.241.92.134
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 147 


x3 try it


cr . Askuller7

**Comment by zPhotons** [comment]
just want to ask i have already inputted the server info and then when i try loggin in putting my username then i put the right password it still saying that i put wrong password but if i try xKore it is all good.

**Comment by zPhotons** [comment]
Why is it always saying wrong password?

**Comment by Roose909** [comment]
I get the following error when I start the program

This program has encountered an unexpected problem. This is probably because
of a recent server update, a bug in this program, or in one of the plugins.
We apologize for this problem. You may get support from IRC or the forums.

A detailed error report has been saved to errors.txt. Before posting a bug
report, please try out the SVN version first. If you are already using the SVN
version, search the forums first to see if your problem had already been solved,
or has already been reported. If you truly believe you have encountered a bug in
the program, please include the contents of the errors.txt in your bug report,
or we may not be able to help you!

The error message is:
Unknown charBlockSize: 147 at src/Network/Receive.pm line 275.

please help!

**Comment by Roose909** [comment]
I get the following error when I start the program

Unknown charBlockSize: 147 at src/Network/Receive.pm line 275.

please help!

**Comment by Roose909** [comment]
Hey guys,

My bot just runs around the map not attacking anything then eventually ends up sitting down.. I have set a lockmap, I've put the Attackauto value at 2 and I see that I have the fields folder and it isn't blank..

anyone know what's wrong?

**Comment by fatyumyum** [comment]
Hello guys, im using this config:

[Ragnarok - Re:Start]
ip 128.241.92.134
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 147

and it not working, error when i click on the server, what i need to do?

**Comment by karendavis22** [comment]
wtf  10 acc got banned today, its harder than botting on renewal

**Comment by Jeffgomz** [comment]
cant log in my bot after maintenance july 19, 2017 T_T hep me

**Comment by Jarlock171** [comment]
This error happened because they changed the server hardware, so probably they should have switched IP and things like /:

**Comment by Jeffgomz** [comment]
waiting to fix :(

**Comment by sctnightcore** [comment]
@Jeffgomz  download new openkore on github

**Comment by Jeffgomz** [comment]
your bot is working?sctnightcore

**Comment by Jarlock171** [comment]
How to fix it? i cant select my character D:
![image](https://user-images.githubusercontent.com/30304674/28397256-dd55cd8c-6cd6-11e7-8516-9cdd824a89b4.png)

**Comment by narueponz** [comment]
i can't edit.

**Comment by brylle0714** [comment]
can u give me link with working restartRO bot? 
after update i got a lot of error pls thank you. i all ready change the ip fromm 34 to 33 after that revpacket error and etc. pls help me thank you.
