### ISSUE TITLE
Packet handler for Change Material-like skill

### ISSUE THREAD

**Issue by cydh** [OpenKore/openkore#65]
Well, if this is solved already, maybe this issue can be ignored.

I'm currently using SVN for r9031 (updated on Feb 28th, 2016)  and the packet handler `0x07E3` and `0x07E4` are still unknown. (Silly me, I just knew that OpenKore has git repo!)
Then, I tried to solve it by this https://gist.github.com/cydh/e1473eb2a242d221e80a42dce4ed7093
By that gist, there is new command to do 'change material', is **cm**.

If it's approved, I can make a new PR later.

**Comment by t3quila** [comment]
wow, you're so great.. thanks for share.

but cydh, why this **cm** cannot spamming?
it's always need 1 **Change Material** Active skill for 1 **cm**.

for example if i create a steel from 10 Tsurugis, that macros could did only 1 skill change material for 10 tsurugis directly,  same as the archer class when using Arrow Craft in bot/macro.

you can see that macros at [http://ragnarokindomania.blogspot.co.id/2012/07/macro-change-material-genetic.html](url)
because this macros could do spamming _cm_, even though it has many errors than your settings lol.
but in fact, this alone is simply superb, you're the best! ^^

**Comment by cydh** [comment]
That's the correct behavior. Just like *identify* does.
If u force spam the packet directly, server will disconnects u.
