### ISSUE TITLE
Character not going back to lockmap after dead [IRO]

### ISSUE THREAD

**Issue by hendra814** [OpenKore/openkore#719]
When Character die, teleport into save point
and then doing storage, sell item dan buy item
after that character stop moving not doing anything.

to back into normal must close the console and open it again

**Comment by oleokoong** [comment]
My bot happen this when finish the autosell sequence, it's just stuck at the location.. religion doesn't help... the only way is keyin move map name and it will move again

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by Aiyaful** [comment]
Can you please check if your character was low hp and in sit. How much zeny do you have? the kore will try to warp your character to the destination.

**Comment by hendra814** [comment]
already check hp/sp and zeny. 
HP/SP already 100% and already buy item flywing, butwing, and potion.
after that character just sit not going to any where.

last i'm tried like @oleokoong put console command move  to lockmap to get work

**Comment by Aiyaful** [comment]
Can you please try this? it will sit/standup at 0 hp. `sitAuto_hp_lower 0
sitAuto_hp_upper 0
sitAuto_sp_lower 0
sitAuto_sp_upper 0
sitAuto_follow 0
sitAuto_over_50 0
sitAuto_idle 1
sitAuto_look
sitAuto_look_from_wall
sitTensionRelax 0`
and change this so that it will use potion instead of regaining hp using sit. `useSelf_item Red Potion {
	hp <60%
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}` if your in renewal, please change your save point except morroc. I tried this in private server because I can't download the installer in iRO.

**Comment by alisonrag** [comment]
continue in #1006
