### ISSUE TITLE
Bring back the statistics server

### ISSUE THREAD

**Issue by kaliwanagan** [OpenKore/openkore#802]
A couple of years ago we had a statistics server that recorded how many users used which versions of kore and on which servers.

I think we should bring it back, but this time try to record a bit more telemetry (like, are there errors on certain issues, which plugins are often used, etc).

We'll need to gather more information about our users in order to be ahead of the issues, instead of waiting for users to bring us up to date on the situation (esp since most devs now don't play RO as much).

We can have it as opt-in that you can either agree to or not (and maybe show it in the logfile that you have agreed to the opt-in in case of debugging).

**Comment by xTriumph** [comment]
> (esp since most devs now don't play RO as much).
LOL, since i started to read the github page i don't give a damn about the game, i just want to test things, even tho i don't know how to code.

This server recording errors would be really good to fix some packet errors from new servers.
About the user agreeing or not, we could use something like: log_server file that has: 
user_Agree ( 1 means yes 2 means no and 0 means that the user didn't answered)
And everytime that kore start it checks to see if the user agree or not, so every new version of kore is realeased the user receives a check box message with the options.

And i would really like to have some reports about NPCs and portals not found logs, so we could just update that faster.

**Comment by alisonrag** [comment]
I agree with statistics server with him we can identify easily some problems
But is important that users have access to data

**Comment by Aiyaful** [comment]
Recorded users is good, you can know which kore server needs to prioritize because of how many users use it. As for version of kore, I think you need an auto patch or update from github directly to it. So that the issue tab will not burst from newbie post.

**Comment by alisonrag** [comment]
merge with #334
