### ISSUE TITLE
Autostoraging all the time?

### ISSUE THREAD

**Issue by JChristofer** [OpenKore/openkore#845]
Hi, K i just downloaded latest openkore, for re:start RO.

I just moved all my old configs which works fine to this new one. Tho something weird happens this time my char keeps autostoraging all the time.. even if its just  50% OW

itemsTakeAuto 2
itemsTakeAuto_party 0
itemsGatherAuto 2
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 7900
itemsTakeAuto_new 0
itemsTakeGreed 0

storageAuto 1
storageAuto_npc geffen 120 62
storageAuto_distance 5
storageAuto_npc_type 3
storageAuto_npc_steps c r1 c r0
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

why?  thanks in advance

**Comment by sctnightcore** [comment]
storageAuto_npc_steps

**Comment by c4c1n6kr3m1** [comment]
itemsMaxWeight_sellOrStore [<percent>]
 Enables auto storage and auto sell when Kore's weight is greater than the one specified, overriding itemsMaxWeight.

http://openkore.com/index.php/ItemsMaxWeight_sellOrStore

**Comment by JChristofer** [comment]
itemsTakeAuto 2
itemsTakeAuto_party 0
itemsGatherAuto 2
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 7900
itemsTakeAuto_new 0
itemsTakeGreed 0

**Comment by JChristofer** [comment]
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 89

What's the difference?  btw i cant seem to find out, itemsMaxWeight_sellOrStore gettin more priority and i dont even have the autosell enabled?

**Comment by moneyisgod** [comment]
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99



>even if its just 50% OW


Yeah, it's working normally.
It's trying to storage, because sellOrStore == 48!

50% is different of "all the time"!


itemsMaxWeight [<percent>]
Enables auto storage and auto sell when Kore's weight is greater than the one specified, this is overrided by itemsMaxWeight_sellOrStore.


itemsMaxWeight_sellOrStore [<percent>]
Enables auto storage and auto sell when Kore's weight is greater than the one specified, overriding itemsMaxWeight.

**Comment by alisonrag** [comment]
Fixed in #829
