### ISSUE TITLE
How to input status on my automacro as arguments?

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#946]
Basically what I want for my macro is for my bot to:

1. Move to a place near my healer/buffer
2. Sit down 
3. Stand up if and only if my HP is 100% and I have Blessings, Increase AGI, and Kyrie Eleison status
4. Move away
5. Hopefully works 💃 

Sadly for #3 only HP 100% works and I do not know how to put the status on my automacro.
I have tried "status not Blessing" and "whenStatusInactive Blessing" as my argument only in my while statement and it doesn't work but I believe the first one should work but it doesn't.

Here is my code.

automacro NearEntranceHeal {
	hp < 30% 
	run-once 0
	exclusive 1
	call {
		do move xmas_dun02 135 132
		pause 1
		do sit
		while (hp < 100%) as loop
			pause 1
		end loop
		do stand 
		pause 1
		do move xmas_dun02 191 130
		pause 1
		stop
		release NearEntranceHeal
	}
}

P.S. This is what I have tried and it doesn't work:
                while (status not Blessing) as loop
			pause 1
		end loop
The error is this "[macro] NearEntranceHeal.call error: error in 3: syntax error in if statement"

Thank you for anyone who responds to this small issue of mine.

**Comment by Nipodemos** [comment]
automacro NearEntranceHeal {
hp < 30%
exclusive 1
#you dont need to declare run-once 0
call {
do move xmas_dun02 135 132
pause 1
do sit
     }
}
#instead of deal with this inside macro, create another automacro:
automacro fully buffed {
hp = 100%
status Blessing
status Increase Agi
status Impositio Manus
status Kyrie Eleilson
call {
do stand
pause 1
do move xmas_dun02 191 130
pause 1
stop
# you dont need to release the other macro
}
}

**Comment by kidbreaker22** [comment]
Okay thank you for pointing out my mistake and giving me a suggestion I'll give it a try

**Comment by Nipodemos** [comment]
sorry for the big words, i dont know how it got so big
